package ch.brewingstand.endpoints.ReviewClasses;

/**
 * Represents a coffee review resource.
 *
 * @param id         Unique identifier of the review (generated by the server).
 * @param coffeeName Name of the coffee being reviewed.
 * @param rating     Rating value (1-5).
 * @param comment    Free text comment.
 */
public record Review(String id, String coffeeName, int rating, String comment) {}
